version: "3.9"
services:

  rtty:
    container_name: rtty
    build: rtty_client
    networks:
      - network
    command: ["rtty", "-s", "-I", "docker_test_client", "-f", "root", "-C", "/etc/rtty/rttys.ca", "-h", "rttys", "-t", "0bc51b8495a39d6b8bcfc149deac5289", "-a", "-c", "/etc/rtty/rtty.crt", "-k", "/etc/rtty/rtty.key"]
    volumes:
      - ./certs:/etc/rtty
    networks:
      - network

  rttys:
    container_name: rttys
    build: rttys
    ports: 
      - 5913:5913
      - 5912:5912
    environment:
      - RTTYS_TOKEN=0bc51b8495a39d6b8bcfc149deac5289
    volumes:
      - ./certs:/etc/rttys:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - network


networks:
  # Declare our private network.  We must declare one for the magic
  # Docker DNS to work, but otherwise its default settings are fine.
  network: {}
